Refactored and added MIT
dVelopment/meteor-random pull request #2
Opened 2020-08-13 14:40 UTC by DavidSichau

I refactored the library similar to how meteor has refactored their random package: https://github.com/meteor/meteor/tree/master/packages/random.

This splits the different concrete implementation into own classes which reduces the required switches in the implementation. And makes it easier to reason about the code.

I also added the MIT LICENCE.

2020-08-21 16:31 UTC, dVelopment requested changes

2020-08-21 16:31 UTC, dVelopment commented on src/AbstractRandomGenerator.ts
> +    id(charsCount: number = 1): string {
comment indicates a default value of 17, but it is set to 1

```suggestion
    id(charsCount: number = 17): string {
```

2020-08-21 16:33 UTC, dVelopment commented
@DavidSichau thank you very much for taking the time to refactor this! Highly appreciated!
could you please just update the default value for the character count in `AbstractGenerator.id`?

2020-08-22 19:45 UTC, DavidSichau commented on src/AbstractRandomGenerator.ts
> +    id(charsCount: number = 1): string {
Thanks for finding this.

2020-08-23 12:56 UTC, dVelopment approved these changes

2020-08-23 12:56 UTC, merged